name: build yolks
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - yolks/**
      - .github/workflows/yolks.yml
permissions:
  contents: read
  packages: write

jobs:
  pushAMD64:
    name: "yolks_AMD64:${{ matrix.yolk }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        yolk:
          - hytale
          
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.lower-repo.outputs.repository }}
          password: ${{ secrets.REGISTRY_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./yolks/${{ matrix.yolk }}
          file: ./yolks/${{ matrix.yolk }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:${{ matrix.yolk }}
            ${{ github.repository_owner == 'nexusatko' && format('ghcr.io/nexusatko/yolks:{0}', matrix.yolk) || '' }}